suppressPackageStartupMessages(library(rgdal))
getPROJ4VersionInfo()
getGDALVersionInfo()
d <- system.file("vectors", package="rgdal")
shps <- ogrListLayers(d)
sapply(shps, function(l) OGRSpatialRef(d, l))
OGRSpatialRef(file.path(d, "airports.gml"), "airports")
OGRSpatialRef(file.path(d, "ps_cant_31.MIF"), "ps_cant_31")
OGRSpatialRef(file.path(d, "Up.tab"), "Up")
OGRSpatialRef(file.path(d, "test_trk2.gpx"), "tracks")
OGRSpatialRef(file.path(d, "PacoursIKA2.TAB"), "PacoursIKA2")
d <- system.file("pictures", package="rgdal")
f <- c("SP27GTIF.TIF", "cea.tif", "erdas_spnad83.tif", "scaleoffset.vrt",
 "test_envi_class.envi")
ds <- GDAL.open(file.path(d, "SP27GTIF.TIF"))
getProjectionRef(ds, OVERRIDE_PROJ_DATUM_WITH_TOWGS84=TRUE)
getProjectionRef(ds, OVERRIDE_PROJ_DATUM_WITH_TOWGS84=FALSE)
GDAL.close(ds)
ds <- GDAL.open(file.path(d, "cea.tif"))
getProjectionRef(ds, OVERRIDE_PROJ_DATUM_WITH_TOWGS84=TRUE)
getProjectionRef(ds, OVERRIDE_PROJ_DATUM_WITH_TOWGS84=FALSE)
GDAL.close(ds)
ds <- GDAL.open(file.path(d, "erdas_spnad83.tif"))
getProjectionRef(ds, OVERRIDE_PROJ_DATUM_WITH_TOWGS84=TRUE)
getProjectionRef(ds, OVERRIDE_PROJ_DATUM_WITH_TOWGS84=FALSE)
GDAL.close(ds)
ds <- GDAL.open(file.path(d, "scaleoffset.vrt"))
getProjectionRef(ds, OVERRIDE_PROJ_DATUM_WITH_TOWGS84=TRUE)
getProjectionRef(ds, OVERRIDE_PROJ_DATUM_WITH_TOWGS84=FALSE)
GDAL.close(ds)
ds <- GDAL.open(file.path(d, "test_envi_class.envi"))
getProjectionRef(ds, OVERRIDE_PROJ_DATUM_WITH_TOWGS84=TRUE)
getProjectionRef(ds, OVERRIDE_PROJ_DATUM_WITH_TOWGS84=FALSE)
GDAL.close(ds)

